import { CropInput, CropPredictionResponse } from '../types/crop';
import { CROP_PREDICTION_ENDPOINT, request } from './api';

interface BackendRecommendation {
  crop: string;
  confidence: number;
}

const normalizeSoil = (soil: string) => {
  const value = soil.toLowerCase();
  if (value.includes('black')) return 'Black soil';
  if (value.includes('red')) return 'Red soil';
  if (value.includes('clay')) return 'Clay soil';
  if (value.includes('sandy')) return 'Sandy soil';
  if (value.includes('laterite')) return 'Laterite soil';
  return 'Alluvial soil';
};

export async function predictCrop(input: CropInput): Promise<CropPredictionResponse> {
  const response = await request<{ recommendations: BackendRecommendation[] }>(
    CROP_PREDICTION_ENDPOINT,
    {
      method: 'POST',
      body: JSON.stringify({
        SOIL: normalizeSoil(input.soilType),
        SEASON: input.season.toLowerCase().startsWith('rabi') ? 'rabi' : 'kharif',
        WATER_SOURCE: input.waterAvailability.toLowerCase().includes('rainfed')
          ? 'rainfed'
          : 'irrigated',
        SOIL_PH: input.soilPh,
        TEMP: input.temperature,
        RELATIVE_HUMIDITY: input.humidity,
        N: input.nitrogen,
        P: input.phosphorus,
        K: input.potassium,
      }),
    }
  );

  const [best, ...alternatives] = response.recommendations;
  if (!best) {
    throw new Error('The backend returned no crop recommendations.');
  }

  const toItem = (recommendation: BackendRecommendation) => ({
    name: recommendation.crop,
    suitability: Number(recommendation.confidence.toFixed(2)),
    summary: 'Recommendation generated by the agricultural prediction model.',
    reasons: ['Based on the farm conditions submitted to the backend.'],
  });

  return {
    bestCrop: toItem(best),
    alternativeCrops: alternatives.map(toItem),
    modelConfidence: Number(best.confidence.toFixed(2)),
    analyzedAt: new Date().toISOString(),
  };
}
